apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumos-lab-frontend
  namespace: lumos-lab-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - lab.dev.lumosgraphy.com
      secretName: lumos-lab-frontend-dev-tls
  rules:
    - host: lab.dev.lumosgraphy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumos-lab-frontend
                port:
                  number: 80
