package com.study.lab.database.bulk;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

@Service
public class BulkInsertService {

    private final JdbcTemplate jdbcTemplate;

    public BulkInsertService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public BulkInsertSimulationResponse simulate(BulkInsertSimulationRequest request) {
        String mode = normalizeMode(request.mode());
        int roundTrips = switch (mode) {
            case "SINGLE_INSERT" -> request.rowCount();
            case "BULK_INSERT" -> 1;
            default -> (int) Math.ceil((double) request.rowCount() / request.batchSize());
        };
        int transactionCount = "SINGLE_INSERT".equals(mode) ? request.rowCount() : 1;

        return new BulkInsertSimulationResponse(
                mode,
                request.rowCount(),
                request.batchSize(),
                roundTrips,
                transactionCount,
                List.of(
                        "rowCount=" + request.rowCount() + "개 데이터를 준비합니다.",
                        "mode=" + mode + " 기준으로 DB 왕복 횟수를 계산합니다.",
                        "roundTrips=" + roundTrips + ", transactionCount=" + transactionCount
                ),
                recommendationFor(mode),
                codeExampleFor(mode)
        );
    }

    @Transactional
    public BulkInsertRunResponse run(BulkInsertRunRequest request) {
        if (jdbcTemplate == null) {
            throw new IllegalStateException("JdbcTemplate is required for actual bulk insert run.");
        }

        String mode = normalizeMode(request.mode());
        createTableIfNeeded();
        jdbcTemplate.update("delete from bulk_insert_lab");

        long startedAt = System.currentTimeMillis();
        List<String> steps = new ArrayList<>();
        steps.add("테이블 준비 후 기존 실습 데이터를 삭제했습니다.");

        if ("SINGLE_INSERT".equals(mode)) {
            for (int index = 1; index <= request.rowCount(); index++) {
                jdbcTemplate.update(
                        "insert into bulk_insert_lab(name, payload, created_at) values (?, ?, ?)",
                        "single-" + index,
                        "payload-" + index,
                        Timestamp.from(Instant.now())
                );
            }
            steps.add("insert 문을 " + request.rowCount() + "번 호출했습니다.");
        } else {
            List<Integer> rows = new ArrayList<>();
            for (int index = 1; index <= request.rowCount(); index++) {
                rows.add(index);
            }
            jdbcTemplate.batchUpdate(
                    "insert into bulk_insert_lab(name, payload, created_at) values (?, ?, ?)",
                    rows,
                    request.batchSize(),
                    (PreparedStatement ps, Integer index) -> {
                        ps.setString(1, mode.toLowerCase(Locale.ROOT) + "-" + index);
                        ps.setString(2, "payload-" + index);
                        ps.setTimestamp(3, Timestamp.from(Instant.now()));
                    }
            );
            steps.add("jdbcTemplate.batchUpdate를 batchSize=" + request.batchSize() + "로 실행했습니다.");
        }

        Integer insertedRows = jdbcTemplate.queryForObject("select count(*) from bulk_insert_lab", Integer.class);
        steps.add("실제 저장된 row 수를 count(*)로 확인했습니다.");

        return new BulkInsertRunResponse(
                mode,
                insertedRows == null ? 0 : insertedRows,
                request.batchSize(),
                System.currentTimeMillis() - startedAt,
                steps,
                codeExampleFor(mode)
        );
    }

    private void createTableIfNeeded() {
        jdbcTemplate.execute("""
                create table if not exists bulk_insert_lab (
                    id bigint generated by default as identity primary key,
                    name varchar(100) not null,
                    payload varchar(255) not null,
                    created_at timestamp not null
                )
                """);
    }

    private String normalizeMode(String mode) {
        String normalized = mode.trim().toUpperCase(Locale.ROOT);
        if ("SINGLE_INSERT".equals(normalized) || "BATCH_INSERT".equals(normalized) || "BULK_INSERT".equals(normalized)) {
            return normalized;
        }
        return "BATCH_INSERT";
    }

    private String recommendationFor(String mode) {
        return switch (mode) {
            case "SINGLE_INSERT" -> "단건 insert는 디버깅은 쉽지만 대량 데이터에서는 DB 왕복이 너무 많아집니다.";
            case "BULK_INSERT" -> "DB별 COPY, LOAD DATA 같은 전용 bulk 기능은 가장 빠를 수 있지만 DB 종속성이 커집니다.";
            default -> "일반적인 애플리케이션에서는 batch insert로 round trip을 줄이는 방식부터 적용해보면 좋습니다.";
        };
    }

    private String codeExampleFor(String mode) {
        if ("SINGLE_INSERT".equals(mode)) {
            return """
                    for (Item item : items) {
                        jdbcTemplate.update("insert into item(name) values (?)", item.name());
                    }
                    """;
        }
        if ("BULK_INSERT".equals(mode)) {
            return """
                    // PostgreSQL COPY, MySQL LOAD DATA처럼 DB 전용 대량 적재 기능을 검토합니다.
                    // 속도는 빠르지만 벤더별 문법과 운영 제약을 같이 봐야 합니다.
                    """;
        }
        return """
                jdbcTemplate.batchUpdate(
                    "insert into item(name) values (?)",
                    items,
                    batchSize,
                    (ps, item) -> ps.setString(1, item.name())
                );
                """;
    }
}
